name: update-version-file

run-name: ${{ github.actor }} is updating version.txt for latest release

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-version"
  update-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Fetches the latest release using the GitHub API
      - name: Query latest release
        run: |
latestReleaseId="$(gh api -H 
"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
